In [1]:
import numpy as np
import array as ar
import pandas as pd
from scipy import *
import torch

In [2]:
# Write a Python program to create an array of 5 integers and display the array items. 

x=np.random.randint(0,10,5)

arr=ar.array("i",[i for i in x])

print(arr.tolist())

[5, 4, 9, 1, 4]


In [3]:
# Write a Python program to append a new item to the end of the array.

x=np.random.randint(0,10,5)

arr=ar.array("i",[i for i in x])

print("Before: ")
print(arr.tolist())

arr.append(int(input("Enter value to append: ")))

print("After: ")
print(arr.tolist())

Before: 
[5, 4, 7, 3, 9]
Enter value to append: 4
After: 
[5, 4, 7, 3, 9, 4]


In [4]:
# Write a Python program to reverse the order of the items in the array.

x=np.random.randint(0,10,5)

arr=ar.array("i",[i for i in x])

print("Before: ")
print(arr.tolist())

print("After: ")
print(arr[::-1].tolist())

Before: 
[5, 6, 6, 2, 5]
After: 
[5, 2, 6, 6, 5]


In [5]:
# Write a Python program to get the number of occurrences of a specified element in an array.

x=np.random.randint(0,10,30)

arr=ar.array("i",[i for i in x])

print(arr.tolist())

n=int(input("\nEnter value whose occurence needs to be estimated in the array: "))

print("No. of Occurrence: ",arr.count(n))

[8, 9, 5, 4, 7, 5, 1, 1, 8, 2, 0, 1, 3, 2, 7, 6, 9, 0, 8, 9, 8, 1, 0, 4, 0, 2, 5, 5, 9, 0]

Enter value whose occurence needs to be estimated in the array: 5
No. of Occurrence:  4


In [6]:
# Write a Python program to append items from inerrable to the end of the array.

x=np.random.randint(0,10,5)

arr=ar.array("i",[i for i in x])

print("Before: ")
print(arr)

print("After: ")
arr.extend(arr)
print(arr)

Before: 
array('i', [0, 2, 9, 6, 2])
After: 
array('i', [0, 2, 9, 6, 2, 0, 2, 9, 6, 2])


In [7]:
# Create a 3x3 boolean array of all TRUE

x=np.full((3,3), True, dtype=bool)

print(x)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [8]:
# Extract all odd numbers from arr

x=np.arange(0,10)

print("Before: ")
print(x)

print("After: ")
print(x[x%2!=0])


Before: 
[0 1 2 3 4 5 6 7 8 9]
After: 
[1 3 5 7 9]


In [9]:
# Replace all odd numbers in arr with -1

x=np.arange(0,10)

print("Before: ")
print(x)

print("\nAfter: ")
x[x%2!=0]=-1
print(x)

Before: 
[0 1 2 3 4 5 6 7 8 9]

After: 
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [10]:
# Replace all odd numbers in arr with -1

x=np.arange(0,10)

print("Before: ")
print(x)

print("\nAfter: ")
y=np.where(x%2==1,-1,x)
print(y)

Before: 
[0 1 2 3 4 5 6 7 8 9]

After: 
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [11]:
# Convert a 1D array to a 2D array with 2 rows

x=np.arange(0,10)
print("Before: ")
print(x)

print("\nAfter: ")
x=x.reshape(2,5)
print(x)

Before: 
[0 1 2 3 4 5 6 7 8 9]

After: 
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [12]:
# Stack arrays a and b vertically

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print("Before: ")
print("a:\n")
print(a)
print("b:\n")
print(b)

print("\nAfter:\n")
x=np.vstack([a,b])
print(x)


Before: 
a:

[[0 1 2 3 4]
 [5 6 7 8 9]]
b:

[[1 1 1 1 1]
 [1 1 1 1 1]]

After:

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [13]:
#Stack arrays a and b

# Method 1:
np.concatenate([a, b], axis=0)

# Method 2:
np.vstack([a, b])

# Method 3:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
# Create the following pattern without hardcoding. Use only numpy functions and the below input array a
# Input: a = np.array([1,2,3])
# Desierd Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

a=np.array([1,2,3])
print("Input:\n")
print(a)

print("\nOutput:\n")
x=np.r_[np.repeat(a,3), np.tile(a,3)]
print(x)

Input:

[1 2 3]

Output:

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [15]:
# Get the common items between a and b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

x=np.intersect1d(a,b)
print(x)

[2 4]


In [16]:
# From array a remove all items present in array b

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

c=np.setdiff1d(a,b)
print(c)

[1 2 3 4]


In [17]:
# Get the positions where elements of a and b match

a=np.random.randint(0,5,20)
b=np.random.randint(0,5,20)

print(a)
print(b)

c=np.where(a==b)
print(c)

[3 3 2 3 2 3 0 3 1 1 4 2 2 1 0 0 1 1 1 2]
[0 0 4 3 0 1 3 4 3 4 4 2 4 1 3 2 1 2 4 2]
(array([ 3, 10, 11, 13, 16, 19]),)


In [18]:
# Get the dot product of two vectors

a=np.random.randint(0,9,9)
a=a.reshape(3,-1)

b=np.random.randint(3,12,9)
b=b.reshape(3,-1)

d=np.dot(a,b)
print(d)

[[ 99  63 128]
 [ 98  56 119]
 [ 89  65 106]]


In [19]:
# Get the outer product of two vectors

a=np.random.randint(0,9,10)
b=np.random.randint(0,9,10)
print("\nVector 1:\n")
print(a)
print("\nVector 2:\n")
print(b)

print("\nOuter Product:\n")
c=np.outer(a,b)
print(c)



Vector 1:

[7 8 0 6 4 8 3 6 4 8]

Vector 2:

[0 5 5 4 5 2 0 2 7 8]

Outer Product:

[[ 0 35 35 28 35 14  0 14 49 56]
 [ 0 40 40 32 40 16  0 16 56 64]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0 30 30 24 30 12  0 12 42 48]
 [ 0 20 20 16 20  8  0  8 28 32]
 [ 0 40 40 32 40 16  0 16 56 64]
 [ 0 15 15 12 15  6  0  6 21 24]
 [ 0 30 30 24 30 12  0 12 42 48]
 [ 0 20 20 16 20  8  0  8 28 32]
 [ 0 40 40 32 40 16  0 16 56 64]]


In [20]:
# Get the cross product of two vectors

a=random.randint(0,9,size=(3,3))
b=random.randint(0,9,size=(3,3))

print("\nMatrix A:\n")
print(a)
print("\nMatrix B:\n")
print(b)

print("\nCross Product: A X B:\n")
print(np.cross(a,b))

print("\nCross Product: B X A:\n")
print(np.cross(b,a))



Matrix A:

[[1 8 8]
 [2 4 8]
 [6 7 5]]

Matrix B:

[[8 1 5]
 [7 7 3]
 [0 6 0]]

Cross Product: A X B:

[[ 32  59 -63]
 [-44  50 -14]
 [-30   0  36]]

Cross Product: B X A:

[[-32 -59  63]
 [ 44 -50  14]
 [ 30   0 -36]]


In [21]:
# Get the determinant of a matrix

x=random.randint(0,9,size=(3,3))
print("Matrix X:\n")
print(x)

print("\nDeterminant of Matrix X:\n")
print(np.round(np.linalg.det(x),5))

Matrix X:

[[7 6 2]
 [4 2 4]
 [5 3 6]]

Determinant of Matrix X:

-20.0


In [22]:
# Get the inner product of two vectors

a=np.random.randint(0,9,size=(3,3))
b=np.random.randint(0,9,size=(3,3))
print("\nVector 1:\n")
print(a)
print("\nVector 2:\n")
print(b)

print("\nInner Product:\n")
c=np.inner(a,b)
print(c)


Vector 1:

[[4 4 4]
 [2 3 6]
 [6 0 7]]

Vector 2:

[[7 6 4]
 [4 0 1]
 [3 1 4]]

Inner Product:

[[68 20 32]
 [56 14 33]
 [70 31 46]]


In [23]:
# Print the Eigen value and Eigen vector of the matrix

x=random.randint(0,9,size=(3,3))
print("Matrix X:\n")
print(x)
value,vect=np.linalg.eig(x)

print("\nEigen Values : ",value)
print("\nEigen Vectors:\n\n",vect)

Matrix X:

[[2 1 6]
 [8 4 4]
 [7 7 5]]

Eigen Values :  [14.44116916+0.j         -1.72058458+2.59501342j -1.72058458-2.59501342j]

Eigen Vectors:

 [[ 0.39231658+0.j         -0.44255892+0.43614022j -0.44255892-0.43614022j]
 [ 0.57549019+0.j          0.63263379+0.j          0.63263379-0.j        ]
 [ 0.71756445+0.j         -0.01964094-0.46185715j -0.01964094+0.46185715j]]


In [24]:
# Get the kronecker product of two matrix

a=random.randint(0,9,size=(3,3))
b=random.randint(0,9,size=(2,3))

print("\nMatrix A:\n")
print(a)
print("\nMatrix B:\n")
print(b)

print("\nKronecker Product: A X B:\n")
print(np.kron(a,b))




Matrix A:

[[7 5 1]
 [8 0 8]
 [0 0 6]]

Matrix B:

[[6 8 1]
 [4 7 8]]

Kronecker Product: A X B:

[[42 56  7 30 40  5  6  8  1]
 [28 49 56 20 35 40  4  7  8]
 [48 64  8  0  0  0 48 64  8]
 [32 56 64  0  0  0 32 56 64]
 [ 0  0  0  0  0  0 36 48  6]
 [ 0  0  0  0  0  0 24 42 48]]


In [25]:
x=random.randint(0,9,size=(3,3))
print("Matrix X:\n")
print(x)

c=np.round(np.linalg.cond(x),3)
print("\nCondition Number for given Matrix-X:\n",c)

Matrix X:

[[3 0 5]
 [8 5 2]
 [1 8 5]]

Condition Number for given Matrix-X:
 2.988


In [26]:
# Get the inverse of a matrix

x=np.random.randint(1,5,size=(3,3))

print("Matrix X:\n")
print(x,"\n")

print("Inverse of Matrix X:\n")
print(np.linalg.inv(x))

Matrix X:

[[4 4 2]
 [1 3 1]
 [1 2 4]] 

Inverse of Matrix X:

[[ 0.38461538 -0.46153846 -0.07692308]
 [-0.11538462  0.53846154 -0.07692308]
 [-0.03846154 -0.15384615  0.30769231]]
